### ISSUE TITLE
Typo in „Get Started Now”

### ISSUE THREAD

**Issue by flashfabrixx** [Snyk/support#2]
After the registration the „Get Started Now” screen is presented to the user. The last instruction got a typo because it should be `snyk protect -i` instead of `snyk project -i`. 
![bildschirmfoto 2015-11-02 um 19 42 07](https://cloud.githubusercontent.com/assets/579869/10890757/26835170-819a-11e5-9e64-d75400e389c8.png)

**Comment by AH7** [comment]
Thanks @flashfabrixx,
It's fixed now.
