### ISSUE TITLE
Cannot delete project/snapshot

### ISSUE THREAD

**Issue by tanepiper** [Snyk/support#4]
Hi there,

I am receiving emails for a project that is no longer active (it's since been split out into smaller microservice projects) but when I log into the dashboard, or look at the CLI there seems to be no option to remove it from snyk?

**Comment by AH7** [comment]
Hi Tane, 

We’re working on the ability to delete snapshots in the current sprint, I’ll be happy to let you know once that has been release.
In the meantime, if you would like to stop receiving notifications for this project send a message to support@snyk.io and we will delete it. 

Best,
Assaf
