### ISSUE TITLE
oAuth providers

### ISSUE THREAD

**Issue by adam-moss** [Snyk/support#5]
Hi,

Do you plan to offer oAuth with providers other than GitHub?  If so is there a timeline for this?

Thanks

**Comment by guypod** [comment]
Hi Adam,

We do plan to add such support, but don't have a set timeline for it. Which providers would you like to see added?

Cheers,
Guypo

**Comment by adam-moss** [comment]
Hi,

Google to start probably, gitlab and bitbucket too :+1: 

Regards :)

**Comment by guypod** [comment]
Closing as we're deprecating this repo in favour of support@snyk.io. Adding more oauth providers is still on the list!
