### ISSUE TITLE
High severity vuln found introduced via snyk@1.14.3

### ISSUE THREAD

**Issue by assaf** [Snyk/support#7]
```
? High severity vuln found in minimatch@0.3.0, introduced via snyk@1.14.3
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:minimatch:20160620
- from: snyk@1.14.3 > recursive-readdir@1.3.0 > minimatch@0.3.0
```

**Comment by adonisv79** [comment]
Hi, this is also happening in ours. hopefully we can get a response here soon.

**Comment by guypod** [comment]
This was resolved that as soon as that vulnerability was disclosed, by releasing a new version of snyk. Can you please upgrade snyk to 1.17.1?

As you can see the new version has no issues: https://snyk.io/test/npm/snyk/1.17.1

While the older one stated here did: https://snyk.io/test/npm/snyk/1.14.3

**Comment by adrukh** [comment]
This is resolved in a newer release. Please run `n install -g snyk` to upgrade, and change the dependency version of snyk in your package to `^1.17.0`.
